"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider, useSelector } from "react-redux";
import { store } from "../redux/store";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Footer, Header, Loader } from "@/components";
import WishDrawer from "@/components/WishDrawer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const loader = useSelector((state: any) => state.loader.loader)

  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Provider store={store}>
            <WishDrawer />
            <Loader visible={loader} />
            <Header />
            {children}
            <Footer />
          </Provider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
